Repository CodeForAfrica/HURUmap-Dashboard, pull requests merged in 2020-07, with the labels that each got.

#19 Number chart description + Article custom fields
  wp-content/plugins/hurumap/package.json
  wp-content/plugins/hurumap/src/ChartDefinition/HurumapChart.js
  wp-content/plugins/hurumap/yarn.lock
  wp-content/themes/hurumap/acf-json/group_5eff3ddd1fda1.json
Labels: bug, enhancement

#20 Other Chart Properties + Reference Data
  wp-content/plugins/hurumap/package.json
  wp-content/plugins/hurumap/src/ChartDefinition/HurumapChart.js
  wp-content/plugins/hurumap/src/Theme.js
  wp-content/plugins/hurumap/yarn.lock
Labels: bug, dependencies, enhancement

#21 [Feature] Domains Whitelist
  wp-content/plugins/hurumap/api.php
  wp-content/themes/hurumap/functions.php
Labels: feature
